/**
 * Constants for VarunaSutra.
 * Indian states, districts, languages, emergency numbers, and other static data.
 * This file is intentionally large — it's a data file, not logic.
 */

/** All Indian states and union territories */
export const INDIAN_STATES: readonly string[] = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const;

/** Major districts per state (subset for demo — cascading dropdown) */
export const STATE_DISTRICTS: Record<string, readonly string[]> = {
  Maharashtra: [
    'Mumbai',
    'Mumbai Suburban',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Kolhapur',
    'Ratnagiri',
    'Sindhudurg',
    'Satara',
    'Sangli',
    'Raigad',
    'Palghar',
  ],
  Delhi: ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'South Delhi', 'West Delhi'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Erode',
    'Vellore',
    'Thanjavur',
    'Kanchipuram',
  ],
  Karnataka: [
    'Bengaluru Urban',
    'Bengaluru Rural',
    'Mysuru',
    'Mangaluru',
    'Hubballi-Dharwad',
    'Belagavi',
    'Gulbarga',
    'Shimoga',
    'Tumkur',
    'Udupi',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Palakkad',
    'Alappuzha',
    'Kannur',
    'Malappuram',
    'Idukki',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'North 24 Parganas',
    'South 24 Parganas',
    'Hooghly',
    'Nadia',
    'Murshidabad',
    'Darjeeling',
    'Jalpaiguri',
    'Siliguri',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Junagadh',
    'Gandhinagar',
    'Kutch',
    'Anand',
    'Mehsana',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Agra',
    'Allahabad',
    'Meerut',
    'Noida',
    'Ghaziabad',
    'Bareilly',
    'Gorakhpur',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Begusarai',
    'Nalanda',
    'Saran',
    'Vaishali',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kadapa',
    'Anantapur',
    'Eluru',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Medak',
    'Rangareddy',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Rewa',
    'Satna',
    'Dewas',
    'Chhindwara',
  ],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Puri',
    'Sambalpur',
    'Balasore',
    'Angul',
    'Dhenkanal',
    'Kendrapara',
  ],
  Assam: [
    'Guwahati',
    'Dibrugarh',
    'Silchar',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Karimganj',
    'Goalpara',
  ],
  Punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Pathankot',
    'Hoshiarpur',
    'Moga',
    'Firozpur',
  ],
  Haryana: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Karnal',
    'Hisar',
    'Rohtak',
    'Sonipat',
    'Yamunanagar',
    'Kurukshetra',
  ],
  Chhattisgarh: [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Raigarh',
    'Jagdalpur',
    'Ambikapur',
    'Dhamtari',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro',
    'Hazaribagh',
    'Deoghar',
    'Giridih',
    'Dumka',
    'Ramgarh',
    'Chaibasa',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Almora',
    'Pithoragarh',
    'Rudraprayag',
    'Chamoli',
    'Tehri Garhwal',
    'Uttarkashi',
    'Pauri Garhwal',
  ],
  Goa: ['North Goa', 'South Goa'],
  'Himachal Pradesh': [
    'Shimla',
    'Kangra',
    'Mandi',
    'Kullu',
    'Solan',
    'Una',
    'Hamirpur',
    'Bilaspur',
    'Sirmaur',
    'Chamba',
  ],
};

/** Emergency numbers relevant to monsoon preparedness */
export const EMERGENCY_NUMBERS = {
  national: '112',
  floodHelpline: '1070',
  ndrf: '1077',
  ambulance: '108',
  childHelpline: '1098',
  womenHelpline: '1091',
  fireService: '101',
  police: '100',
} as const;

/** State disaster management authority info (subset) */
export const SDMA_CONTACTS: Record<string, { name: string; phone: string }> = {
  Maharashtra: { name: 'Maharashtra SDMA', phone: '022-22027990' },
  Kerala: { name: 'Kerala SDMA', phone: '0471-2364424' },
  Karnataka: { name: 'Karnataka SDMA', phone: '080-22340676' },
  'Tamil Nadu': { name: 'Tamil Nadu SDMA', phone: '044-28524915' },
  'West Bengal': { name: 'West Bengal SDMA', phone: '033-22143526' },
  Gujarat: { name: 'Gujarat SDMA', phone: '079-23251900' },
  'Andhra Pradesh': { name: 'Andhra Pradesh SDMA', phone: '0863-2340525' },
  Telangana: { name: 'Telangana SDMA', phone: '040-23456789' },
  Odisha: { name: 'Odisha SDMA', phone: '0674-2534177' },
  Assam: { name: 'Assam SDMA', phone: '0361-2237219' },
  Bihar: { name: 'Bihar SDMA', phone: '0612-2217310' },
  'Uttar Pradesh': { name: 'Uttar Pradesh SDMA', phone: '0522-2236772' },
  Delhi: { name: 'Delhi DDMA', phone: '011-22392627' },
  Rajasthan: { name: 'Rajasthan SDMA', phone: '0141-2227296' },
  'Madhya Pradesh': { name: 'Madhya Pradesh SDMA', phone: '0755-2441361' },
};

/** Blood group options */
export const BLOOD_GROUPS: readonly string[] = [
  'A+',
  'A-',
  'B+',
  'B-',
  'AB+',
  'AB-',
  'O+',
  'O-',
  'Unknown',
] as const;

/** Relationship options */
export const RELATIONSHIPS: readonly string[] = [
  'Self',
  'Spouse',
  'Father',
  'Mother',
  'Son',
  'Daughter',
  'Brother',
  'Sister',
  'Grandfather',
  'Grandmother',
  'Uncle',
  'Aunt',
  'Other',
] as const;
